### ISSUE TITLE
Import from Notions + CSV

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#1]
**High-level:**
Improve quality & variety of imports available to Anytype users

**Related threads & feature requests:**
https://community.anytype.io/t/notion-import-include-properties-as-relations/3961
https://community.anytype.io/t/something-similar-to-a-set-but-local-to-the-page/8070/2
https://community.anytype.io/t/import-from-obsidian-md/2359
https://community.anytype.io/t/joplin-migration-or-import/7967

**Comment by Narvey** [comment]
Please also allow import from logseq eventually. I'm happy to help write the importer as I know the logseq format at least fairly well. https://matrix.to/#/@narvey:matrix.org or https://community.anytype.io/u/narvey

**Comment by eleazar7** [comment]
Thank You AnyType for working on this. 
I don't see these on this list?

https://community.anytype.io/t/ability-to-import-bookmark-html-files-into-anytype/6023/2
https://community.anytype.io/t/import-from-csv-excel-calc-google-sheets-etc/3968/3
https://community.anytype.io/t/import-from-evernote/3868

**Comment by eleazar7** [comment]
https://community.anytype.io/t/upnote-import-option/8253
https://community.anytype.io/t/option-to-import-markdown-files-into-app/7454

**Comment by fuksman** [comment]
@Narvey, @eleazar7, thank you for your suggestions!
We aim to deliver imports from .md and Notion with an Open Beta release. Imports from .html, .csv, and .txt are planned for later.
We also believe in the power of community and hope more import and export options will be created by contributors. We already design Import API and will release it later this year.
