### ISSUE TITLE
Integrate new infrastructure (sync improvements)

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#10]
**High Level:**
Integration of Anysync protocol 

**Related Threads & Feature Requests:**
https://community.anytype.io/t/syncing-barely-works/5511
https://community.anytype.io/t/ipfs-node/7391
https://community.anytype.io/t/first-impression-syncing-doesnt-work-well/4719/11

**Comment by tennox** [comment]
Are there any (public) details on this protocol?
I'm curious how far down the rabbithole you went as there are many ipfs alternatives / aspiring successors emerging - like [iroh recently](https://www.n0.computer/blog/a-new-direction-for-iroh/), or [fission carmirror](https://github.com/fission-codes/spec/tree/main/car-pool), or some others I don't remember...

(and we're also building p2p syncing stuff based on IFPS)

**Comment by charlotte-chiang** [comment]
Thanks for the question! Team's currently writing documentation on the protocol, it will be shared when we open our repos. Once available, add the link(s) in comment to this issue as well.

**Comment by ahmedwael216** [comment]
with the beta released. shouldn't this be closed?

**Comment by charlotte-chiang** [comment]
Closing now!
