### ISSUE TITLE
New Onboarding Flow

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#11]

**Comment by Erindale** [comment]
Fantastic to see this on the roadmap!
The ease of entry is going to have very, very real consequences to the long-term health of the project.
Building user profiles and designing a concise pedagody for those will pay dividends.

**Comment by charlotte-chiang** [comment]
Thanks @Erindale! Definitely looking forward to introducing this step-by-step.

**Comment by hit-lacus** [comment]
Is there any link to introduce what is this "onboarding flow" is? Thx.

**Comment by jmetrikat** [comment]
@charlotte-chiang This issue can now be closed since the new onboarding has been introduced in the latest version, right?

**Comment by charlotte-chiang** [comment]
@jmetrikat thanks, closing!!
