### ISSUE TITLE
Open all repos to public

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#14]
**High level:**
Open read-only of all anytype repositories so community can verify our code

**Related Threads/Feature Requests:**
https://community.anytype.io/t/why-is-the-code-not-open-source-at-the-moment/7735
https://community.anytype.io/t/open-source-release-date/6641

**Comment by Narvey** [comment]
Does this include protobuf files as mentioned in https://community.anytype.io/t/when-can-anytype-publish-the-protobuf-files/9610 ?

**Comment by fuksman** [comment]
@Narvey, yes, we will open "any-block" (that's how we refer to it) under the MIT license. 
We may need to put in extra effort to document it, so any help from the contributors community would be much appreciated.

**Comment by TheSunCat** [comment]
I would be happy to contribute, but what does "read-only" imply in that case? How can we contribute to a read-only repository?

**Comment by SamBouwer** [comment]
Read only means you can only read, and not write. The repositories will be made ready for contributions at a later time, and I expect this will be clearly communicated beforehand as many people are excited to get started with contributions :)
