### ISSUE TITLE
Multiplayer MVP

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#16]
**High level:**
Permit sharing, access control, & collaboration within Anytype ecosystem

**Related Threads/Feature Requests:**
https://community.anytype.io/t/collaboration-team-environment/1079
https://community.anytype.io/t/collaboration/1375/6
https://community.anytype.io/t/collaboration-multi-user-team-environments/5048
https://community.anytype.io/t/public-content-readonly-and-collaborative-editing/2292

**Comment by poweredupbass** [comment]
Yessss! Can we have 'Access Control' available via API with AES256 encrypted inputs? I want to use NFC tokens AND pin codes to slowly reveal access to our company's scavenger hunts! Pls & Ty!! I would LOVE to build my app here instead of having to make my own with my dev team. I know that what I'm asking for is a highly sophisticated DB but your tech and vision is the only that I want to go with.

**Comment by elquimista** [comment]
Can't wait for this! This is the only major thing that keeps me from using Anytype as my primary app. For now, I am staying with Almanac.

**Comment by tinkerbits** [comment]
Likewise; I'm really looking forward to this. Would love to use Anytype together with my girlfriend to run our little art business.

**Comment by Chinoman10** [comment]
I can't state how important this is to us.
Please 🙏  and thank you!

**Comment by digitalbirth** [comment]
Collaboration is the key to using your knowledge base, can't wait to have this feature

**Comment by NilsBruhnCodes** [comment]
Is it still realistic to have this update in 2024 Q1? I would love to test it with my team!

**Comment by fuksman** [comment]
Hi @NilsBruhnCodes, we plan to deliver this in late April.

**Comment by StefanFabian** [comment]
Will this also allow having spaces on different networks?
I want to self-host for private use and a separate self-hosted sync node for work, which will be shared with colleagues.
Currently, it looks like this would only be possible by using separate accounts and logging out/in whenever I want to switch spaces.
