### ISSUE TITLE
Custom storage location

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#20]
**High level:**
Allow user to specify where Anytype data lives on their device

**Related threads/Feature requests:**
https://community.anytype.io/t/custom-storage-location/994
https://community.anytype.io/t/choose-the-drive-or-location-to-install-the-software-now-it-is-directly-getting-installed-in-c-drive/6456/2
https://community.anytype.io/t/more-choice-for-installation/8077/2

**Comment by danaugrs** [comment]
Awesome. What about specifying which devices the data is stored on? Ideally all of one's data would be stored in anytype, but that's too much for e.g. a phone. So a user should be able to prioritize which data to keep local where. Are there any plans for this?

**Comment by CLi321** [comment]
Excuse me, what is the format in which the documents stored in the data stored in the specified location will be stored? Can it be in markdown format?

**Comment by fuksman** [comment]
@danaugrs, we plan to implement this, but not within the scope of custom storage location.

@CLi321, all data is stored in the [any-block](https://github.com/anyproto/any-block) format. You can export objects to Markdown format.

**Comment by developomp** [comment]
Why is this issue closed? It doesn't appear to be implemented yet.

**Comment by apronkin** [comment]
It's released in the 0.40.0 version for a desktop

**Comment by danaugrs** [comment]
Is the issue I described in [my comment above](https://github.com/anyproto/roadmap/issues/20#issuecomment-1773858250) tracked anywhere?

**Comment by jayash4444** [comment]
I am using the lastest Anytype version for desktop


![Image](https://github.com/anyproto/roadmap/assets/168435437/0d3902fb-6b33-47e8-b5eb-4f71e21ae750)

There is only an option to open the directory, not to change it.



![Image](https://github.com/anyproto/roadmap/assets/168435437/0e4539ff-ca64-4425-b937-82ccaee3b14a)


Please show us in a video or documentation or images how to actually change the directory, this feature will finally allow me to start using AnyType

**Comment by jayash4444** [comment]
As usual @apronkin you ignore this question for weeks in community private message and comment in the community forum and now also in GitHub comment. Why not reply and clarify the situation instead of continuously claiming it's closed and ignoring all comments that point otherwise? Ridiculous.

**Comment by apronkin** [comment]
Have you tried to log out and choose a new location when you log in?

**Comment by charlotte-chiang** [comment]
Hi @jayash4444 as described in our [release notes](https://community.anytype.io/t/anytype-desktop-0-40-0-multiplayer-released/20219) for 0.40.0, this change was included in the last release - to use it, you'll need to first logout, click the settings wheel in the top-right corner, and which opens a menu as below. From there you can specify the location.


![Image](https://github.com/anyproto/roadmap/assets/110032964/37b5fee3-2b38-4f1d-945e-160c0fff3166)

**Comment by jayash4444** [comment]
Thank you for your reply.
No, after logging out then logging back in it still shows as I shared in the previous image (only the option to open the location).
I tried quitting the application as well, same result.
I tried creating a new vault, also same result.

**Comment by ra3orblade** [comment]
> Thank you for your reply. No, after logging out then logging back in it still shows as I shared in the previous image (only the option to open the location). I tried quitting the application as well, same result. I tried creating a new vault, also same result.

You are looking in the wrong place

https://github.com/anyproto/roadmap/assets/1450818/bad3ae04-46c1-4c16-a8a1-f2c76a66cf0c

**Comment by jayash4444** [comment]
This method worked, thank you so much @ra3orblade
Time to dive into Anytype! :D

**Comment by jayash4444** [comment]
This breaks the app completely btw @ra3orblade @charlotte-chiang @apronkin 
To replicate choose a custom location to be an external HDD or SSD and select the Network to be Local-only
Create the vault and save the key
Safely remove the External HDD or SSD and connect it to another PC or Laptop
Open Anytype and use the same settings (local only and the same custom location)
When you put in the Key for the existing vault it will keep loading and do nothing
If you quit the app and open it again it will be permanently stuck on searching for your vault and you can't do anything unless you completely uninstall the app

That makes this feature unusable and defeats the purpose, unless I'm doing something wrong from my end

**Comment by jayash4444** [comment]
https://community.anytype.io/t/custom-storage-location-breaks-the-app-when-its-on-external-storage/20677/3

**Comment by varunpalekar** [comment]
Unable to use this feature on iPhone 13 Pro, no option of Vault Data location.
Application version : 0.32.3
Build number: 2
Library version: v0.35.6
