### ISSUE TITLE
Web clipper

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#22]
**High Level**
Save snippets from the web directly as Anytype objects

**Related Threads & Feature Requests**
https://community.anytype.io/t/future-plugin-extension-api-ideas/1397/23
https://community.anytype.io/t/web-clipper-ability-to-create-template-for-web-clipper/2323
https://community.anytype.io/t/web-clipper/993

**Comment by osirisberbesia** [comment]
A big goal!!

**Comment by ikalosh** [comment]
looking forward to it!

**Comment by papalouf** [comment]
Hello AnyTeam, any news about this feature ? Is it going well ?

**Comment by orezeno22** [comment]
A big node in my workflow 👍

**Comment by szewc** [comment]
Fingers crossed.

**Comment by securegh** [comment]
The only feature holding me from daily driving Anynote.

**Comment by anishvash** [comment]
Any Update on when it will be available?

**Comment by fuksman** [comment]
Approximately in February.

**Comment by 3xp11i** [comment]
> Approximately in February.

Glad to know that! Eagerly waiting for it <3
