### ISSUE TITLE
Multiple personal spaces

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#23]
**High level:**
Move from single-space to multi-space concept, where user can apply different privacy settings, objects, & relations to each space

**Related threads/Feature requests:**
https://community.anytype.io/t/separate-accounts-installations-workspaces-and-sync-options/1250

**Comment by v-c0de** [comment]
Can't wait for this one! 
Will be a game changer!

**Comment by charlotte-chiang** [comment]
@v-c0de SAME 🤠

**Comment by raphmim** [comment]
Curious about “where user can apply different privacy settings”. Do privacy settings mean that this will include some basic version of sharing or publishing?

**Comment by Chinoman10** [comment]
I wonder how far along this is?
Have also been waiting a few months for this...
