### ISSUE TITLE
Collections 

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#3]
**High-level:**
Ability to store lists of data with user selected content. Kinda like sets but users chooses what objects are inside. 

**Related threads & feature requests:**
https://community.anytype.io/t/something-similar-to-a-set-but-local-to-the-page/8070/2
https://community.anytype.io/t/dashboard-as-a-type-with-layouts/4776

**Comment by Lite5h4dow** [comment]
will this have compatibility with inline sets?

**Comment by charlotte-chiang** [comment]
@Lite5h4dow Hey! Not exactly, collections will work a bit differently as they're less like filters (sets) and more like folders, where you can create any Object type. AFAIK inline collections are not planned for the first iteration, but will be introduced in the future :)
