### ISSUE TITLE
Allow self-hosting

### ISSUE THREAD

**Issue by charlotte-chiang** [anyproto/roadmap#9]
**High Level:**
Allow users to configure storage location & host their own Anytype nodes 

**Related Threads/Feature Requests:**
https://community.anytype.io/t/local-hosting-of-database-or-where-is-the-data-being-storage/7376
https://community.anytype.io/t/is-there-a-way-to-limit-storage-of-data-only-local/6982
https://community.anytype.io/t/user-defined-storage-backend/1575
https://community.anytype.io/t/paranoid-new-user-who-doesnt-like-autosync/7445
https://community.anytype.io/t/for-those-that-have-asked-for-it-what-form-of-nextcloud-integration-do-you-want/7181/2

**Comment by Lite5h4dow** [comment]
cant wait for this!

**Comment by kanersps** [comment]
This feature will make Anytype the best note taking app, period. The standard encryption is already massive and made me switch, but vendor supported self hosting will be the icing on the cake!

**Comment by Narvey** [comment]
It should be noted that Anytype _used_ to have this feature: Every device was an Anytype node. This feature was taken away when Anytype Beta moved to the Anysync protocol. The only reason this needs to be on the roadmap again is to restore feature parity with Anytype Alpha.

**Comment by fuksman** [comment]
@Narvey 
Self-hosting here is about being able to host your own backup-node, not the p2p capabilities of clients-as-a-node. 

`any-sync` should not affect the p2p connection between your devices on the same local network.
If you started having problems with p2p after recent releases, please provide us with more information or submit a bug report: https://community.anytype.io/t/about-the-bug-reports-category/957

**Comment by thoward27** [comment]
Just to clarify, is there any intention from the anytype team to allow users to opt-out of using their backup node? I would personally really like to run my own node, but if that's not possible I'd rather just use P2P then have my notes in the cloud. 

This application looks super exciting and this specific functionality is the only thing preventing me from jumping in whole-heartedly!

**Comment by fuksman** [comment]
@thoward27 it's already possible to run your own node. Please check [this link](https://tech.anytype.io/how-to/self-hosting) for details. It requires technical skills, and we aim to simplify the process in the future with the help of the contributors' community.

**Comment by thoward27** [comment]
@fuksman thank you for the speedy reply and for the link! 

After giving it a read, it looks like the only way to use the self-hosted node is to build the client from source, is that correct? If so, do you or the team have any issues tracking the ability for users to configure their backup nodes in the client itself? I would like to follow that issue if so.

Best,
Tom

**Comment by fuksman** [comment]
@thoward27 that's true for now, and we plan to allow apps configuration in future releases. We don't have a public issue for this, so I've saved a link to your profile and will mention you when we update a public roadmap.

**Comment by chris-sanders** [comment]
I too am interested in self-hosting if you could notify me when the clients have an option to select your own server. I'm happy to help with Kuberentes Helm chart development as that's how I would intend to run it I just don't want to compile client applications for myself or my family.

**Comment by fuksman** [comment]
@chris-sanders it appears that we will include this option in our October release.

**Comment by JIAMING-LI** [comment]
Is this still the case since it is already the end of October

**Comment by fuksman** [comment]
Hey @JIAMING-LI, we're sorry for the delay; the team was focused on other features, and this one will be delivered in a later release.

**Comment by elquimista** [comment]
Why is this marked done when it's not released yet?

**Comment by fuksman** [comment]
@elquimista the self-hosting capability has been released. You can find the instructions on how to do it [here](https://tech.anytype.io/how-to/self-hosting). We will also be releasing a simplified flow for app configuration. However, self-hosting is already accessible to everyone.

**Comment by elquimista** [comment]
This instruction is what I read already months ago. This works but, like someone pointed out, this involves building clients manually which is inconvenient (not to mention even more inconvenience for certificate-related stuff for iOS app building). I was referring to capability of simply specifying custom sync server URL within the client app. Is that possible and is it on the roadmap?

**Comment by fuksman** [comment]
@elquimista, the option to pass a self-hosted network configuration to the app will be released in the next update (following the release of multiple spaces). I have renamed [this feature](https://github.com/orgs/anyproto/projects/1?pane=issue&itemId=34713319) in the roadmap to reflect this.
